name = "Hugo Skeleton CSS"
license = "MIT"
licenselink = "https://github.com/glebt/hugo_skeleton_css/blob/master/LICENSE.md"
description = "Starter Hugo theme (based on Blank) with Skeleton CSS"
homepage = "https://github.com/glebt/hugo_skeleton_css"


